name = "operonatlas-api"
main = "src/main.py"
workers_dev = false
preview_urls = false
compatibility_date = "2026-07-25"
compatibility_flags = ["python_workers", "disable_python_external_sdk"]

[vars]
DOWNLOAD_BASE_URL = "https://downloads.operonatlas.org"

[limits]
cpu_ms = 1000

[[d1_databases]]
binding = "DB"
database_name = "operon_atlas_1_1_0"
database_id = "bbe6b18b-4980-4428-9af3-b506d51268c3"

[[r2_buckets]]
binding = "DOWNLOADS"
bucket_name = "operonatlas-downloads"

[[ratelimits]]
name = "API_RATE_LIMITER"
namespace_id = "1001"

  [ratelimits.simple]
  limit = 120
  period = 60

[[ratelimits]]
name = "HEAVY_API_RATE_LIMITER"
namespace_id = "1002"

  [ratelimits.simple]
  limit = 30
  period = 60
